-- =============================================================================
-- 本文件已弃用：仅补 category_id 会导致后续仍缺 gender_req、work_arrangement 等列。
-- 请在 Supabase SQL Editor 打开并执行：
--   supabase/SQL_EDITOR_一键补全_jobs_发布所需列.sql
-- 然后：Settings → API → Reload schema → 刷新发布页。
-- =============================================================================
