-- 岗位主表 jobs：与前端 Vite 项目统一（勿与 part_time 混用）
-- 在 Supabase SQL Editor 中可整段执行；已存在对象时用 IF NOT EXISTS / DROP IF EXISTS 保证可重复执行

-- ---------------------------------------------------------------------------
-- 1. 表结构（若已有 jobs 表，仅补充缺失列）
-- ---------------------------------------------------------------------------
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category_id bigint references public.job_category (id),
  title text not null default '',
  address text,
  price text,
  salary numeric not null default 0,
  work_time text,
  gender_req text default '不限',
  phone text,
  wechat text,
  content text,
  user_id uuid references auth.users (id) on delete set null,
  nickname text,
  status integer not null default 1,
  cover_image text,
  work_arrangement text
);

comment on table public.jobs is '校园兼职岗位；status=1 为已上线可对访客展示';
comment on column public.jobs.status is '1=已上线 0=下架/草稿';

alter table public.jobs alter column status set default 1;

-- 常见缺失列（老库升级：表已存在但缺列时 create table 不会补全）
-- category_id 勿与 REFERENCES 写在一行：若 job_category 尚未建好，整句失败会导致列加不上
alter table public.jobs add column if not exists category_id bigint;
alter table public.jobs add column if not exists cover_image text;
alter table public.jobs add column if not exists gender_req text default '不限';
alter table public.jobs add column if not exists nickname text;
alter table public.jobs add column if not exists status integer default 1;
alter table public.jobs add column if not exists work_arrangement text;
alter table public.jobs add column if not exists salary numeric not null default 0;

-- category_id 外键（表与列已存在后再加，避免整段迁移失败）
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'job_category') then
    if not exists (
      select 1 from pg_constraint c
      join pg_class t on c.conrelid = t.oid
      where t.relname = 'jobs' and c.conname = 'jobs_category_id_fkey'
    ) then
      alter table public.jobs
        add constraint jobs_category_id_fkey
        foreign key (category_id) references public.job_category (id);
    end if;
  end if;
end $$;

-- 历史空值：视为已上线
update public.jobs set status = 1 where status is null;

-- ---------------------------------------------------------------------------
-- 2. 从 part_time 一次性迁移（若仍存在旧表且需合并数据，取消注释并视情况调整）
-- ---------------------------------------------------------------------------
-- insert into public.jobs (
--   created_at, category_id, title, address, price, work_time, gender_req,
--   phone, wechat, content, user_id, nickname, status, cover_image
-- )
-- select
--   p.created_at, p.category_id, p.title, p.address, p.price, p.work_time,
--   coalesce(p.gender_req, '不限'), p.phone, p.wechat, p.content, p.user_id,
--   p.nickname, coalesce(p.status, 1), p.cover_image
-- from public.part_time p
-- where not exists (select 1 from public.jobs j where j.id = p.id);

-- ---------------------------------------------------------------------------
-- 3. 索引（列表分页、分类、状态筛选）
-- ---------------------------------------------------------------------------
create index if not exists idx_jobs_status_created_at on public.jobs (status, created_at desc);

create index if not exists idx_jobs_category_status_created
  on public.jobs (category_id, status, created_at desc);

create index if not exists idx_jobs_user_id on public.jobs (user_id);

-- ---------------------------------------------------------------------------
-- 4. RLS：访客可读已上线；登录用户可读自己草稿/下架；本人可改删
-- ---------------------------------------------------------------------------
alter table public.jobs enable row level security;

drop policy if exists "jobs_select_visible" on public.jobs;
create policy "jobs_select_visible"
  on public.jobs
  for select
  to anon, authenticated
  using (
    status = 1
    or (auth.uid() is not null and auth.uid() = user_id)
  );

drop policy if exists "jobs_insert_authenticated" on public.jobs;
create policy "jobs_insert_authenticated"
  on public.jobs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "jobs_update_own" on public.jobs;
create policy "jobs_update_own"
  on public.jobs
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "jobs_delete_own" on public.jobs;
create policy "jobs_delete_own"
  on public.jobs
  for delete
  to authenticated
  using (auth.uid() = user_id);
